name: CI

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - '*.*'
        paths-ignore:
            - README.md

jobs:
    test-web:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
            - uses: actions/checkout@v4
            - name: Restore Dependency Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
#    test-ios:
#        runs-on: macos-latest
#        timeout-minutes: 30
#        strategy:
#            matrix:
#                xcode:
#                    - /Applications/Xcode_12.4.app
#        steps:
#            - run: sudo xcode-select --switch ${{ matrix.xcode }}
#            - uses: actions/setup-node@v1
#              with:
#                  node-version: 14.x
#            - uses: actions/checkout@v2
#            - name: Restore Dependency Cache
#              uses: actions/cache@v1
#              with:
#                  path: ~/.npm
#                  key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
#            - run: npm install
#            - run: npm run verify
#              working-directory: ./ios
    test-android:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 21

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
              working-directory: ./android

            - name: Cache .gradle
              uses: actions/cache@v4
              with:
                  path: .gradle
                  key: ${{ runner.os }}-dotgradle-${{ hashFiles('**/build.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-dotgradle-

            - name: Cache gradle
              uses: actions/cache@v4
              with:
                  path: ~/.gradle
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Install Capacitor Android dependency
              run: npm ci

            - name: Run Tests
              run: ./gradlew test
              working-directory: ./android
